import { getFirestore, collection, doc, addDoc } from "firebase/firestore"
import { User } from "src/types" // Import your User type definition

const db = getFirestore()

/**
 * Creates user document in Firestore on account creation
 * @param userId - The user ID generated by Firebase Authentication
 * @param email - The email the user used to register
 */
export const createUserDoc = async (
  userId: string,
  email: string
): Promise<void> => {
  // User document reference
  const userDocRef = doc(collection(db, "users"), userId)

  const user: User = {
    email,
    username: "",
    profilePictureUrl: "",
    uid: userId,
    phoneNumber: "",
    secondaryEmail: "",
    lastLogin: new Date().toISOString(),
    accountCreationDate: new Date().toISOString(),
    lastActivity: new Date().toISOString(),
    loginSource: "web",
    language: "en-US",
    timezone: "UTC",
    newsletterSubscription: false,
    savedItems: [],
    searchHistory: [],
    userSettings: {},
    subscriptionType: "free",
    subscriptionExpiry: null,
    twoFactorAuthenticationEnabled: false,
    accountRecoveryOptions: {},
    termsAndConditionsAccepted: new Date().toISOString(),
    privacyPolicyAccepted: new Date().toISOString(),
    gdprConsent: false,
    connectedAccounts: {},
  }

  // Create userData sub-collection
  const userDataCollectionRef = collection(userDocRef, "userData")

  // Add default data to userData sub-collection
  await addDoc(userDataCollectionRef, user)
}
